[phases.install]
dependsOn = [] # Tells it not to rely on default provider steps
cmds = ["npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[deploy]
startCommand = "npm run start"